stages:
  - lint
  - test
cache:
  key: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}"
  paths:
  - .cache/pip/
lint:
  stage: lint
  image: python:3.11-slim
  before_script:
    - python -m pip install --upgrade pip
    - pip install --no-input --cache-dir .cache/pip -r requirements-dev.txt
    - export PYTHONPATH="$CI_PROJECT_DIR"
  script:
    - ruff check .
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - ruff.log
  after_script:
    - ruff check . || true | tee ruf.log
test:
  stage: test
  image: python:3.11-slim
  before_script:
    - python -m pip install --upgrade pip
    - pip install --no-input --cahe-dir .cache/pip -r requirements-dev.txt
    - export PYTHONPATH="$CI_PROJECT_DIR"
   script:
    - pytest -q --junitxml=report.xml
  artifacts:
    when: always
    expire_in: 1 week
    reports:
      junit: report.xml
    paths:
      - report.xml
      - .pytest_cache
